CREATE TABLE TARIFFS (
    TARIFF_ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    MONTHLY_FEE DECIMAL(10, 2),
    DATA_LIMIT INT,
    MINUTE_LIMIT INT,
    SMS_LIMIT INT
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CITY VARCHAR(50),
    SIGNUP_DATE DATE,
    TARIFF_ID INT,
    CONSTRAINT FK_Customers_Tariff FOREIGN KEY (TARIFF_ID) 
    REFERENCES TARIFFS(TARIFF_ID)
);

CREATE TABLE MONTHLY_STATS (
    ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    DATA_USAGE INT,
    MINUTE_USAGE INT,
    SMS_USAGE INT,
    PAYMENT_STATUS VARCHAR(20),
    CONSTRAINT FK_Stats_Customer FOREIGN KEY (CUSTOMER_ID) 
    REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE INDEX IDX_Customer_City ON CUSTOMERS(CITY);
CREATE INDEX IDX_Payment_Status ON MONTHLY_STATS(PAYMENT_STATUS);